### PR TITLE
go-waku: update DNS discovery URL entree

### PR DESCRIPTION
**Pull request by yakimant**

### CODE REVIEW

**Comment by yakimant** [comment]
Deployed to test stage

**Review by jakubgs — CHANGES_REQUESTED** [review]
Why are we creating a file just to add one line to it? You can just use a map.

Doing this obscures configuration, one could easily think there's no DNS discovery URL set.

Also bad commit title, it should be something like: `go-waku: update DNS discovery URL entree`.

**Comment by yakimant** [comment]
Agree, looks better with map!

**Comment by yakimant** [comment]
Deployed to prod.

**Review by jakubgs — APPROVED** [review]

**Pull request merged**
